### ISSUE TITLE
About Baselines

### ISSUE THREAD

**Issue by lsyysl9711** [styanXDU/TITAN-evaluation-master#1]
Hi! 

Your proposed dataset is very interesting and I would like to do some research based on TITAN. 

However, I did not find any codes for implementing baselines models on your dataset mentioned in the paper. So could you also release the baseline codes for this dataset so that I can have some references when implementing my own codes?

Thank you very much!

**Comment by styanXDU** [comment]
Thanks for being interested in our dataset! We followed the original baseline codes which you can find through those SOTA papers and revised the parameters to achieve their best results on TITAN. For further study, we provide an evaluation method and upload evaluation codes, where you can process your generation file into the corresponding format and run the evaluate.py file to evaluate your model.

**Comment by lsyysl9711** [comment]
Thanks for replying me!

I find your another repo https://github.com/styanXDU/TITAN. Since both repos contain datas. So I would like to know which one should I use for mixed-initiative interaction task(Both readme files say that they are the mixed-initiative dataset)?

Currently, I am assuming that datas contained in this repo are what I want. But the data directory contains a directory called MULTIWOZ 2 2. So does this mean multiwoz 2.2?(I remember that the dataset used in paper is multiwoz2.1).

Another thing I would like to confirm is that whether I should use the preprocessing file in https://github.com/styanXDU/TITAN? Since you create a new dataset and the processing file is borrowed from another repo which is used for original multiwoz2.1, I would like to whether we should modify this processing file somehow?

For example in original db of multiwoz2.1, we have a file called value_set.json, while in this repo I can not fine this file.

**Comment by styanXDU** [comment]
Thanks! Please conduct your further experiment based on styanXDU/TITAN-evaluation-master,while https://github.com/styanXDU/TITAN is an early version of dataset and codes, we improve our data and release the final version on the directory TITAN-evaluation-master, sorry for the confusion and we may remove the other one. Besides, the data format we use is Multiwoz 2.1, but at first we try to use the 2.2 version, which has a little difference on the content but big difference on the data format. So you can use the one under multiwoz 2 2 but the real format is multiwoz 2.1. The processing file in TITAN-evaluation-master is for TITAN, which we reconstructed. Again, thanks for your question and sorry for the trouble we caused.

2023-09-17 22:04:52"Suyu Liu" ***@***.***>写道：

Thanks for replying me!

I find your another repo https://github.com/styanXDU/TITAN. Since both repos contain datas. So I would like to know which one should I use for mixed-initiative interaction task(Both readme files say that they are the mixed-initiative dataset)?

Currently, I am assuming that datas contained in this repo are what I want. But the data directory contains a directory called MULTIWOZ 2 2. So does this mean multiwoz 2.2?(I remember that the dataset used in paper is multiwoz2.1).

Another thing I would like to confirm is that whether I should use the preprocessing file in https://github.com/styanXDU/TITAN? Since you create a new dataset and the processing file is borrowed from another repo which is used for original multiwoz2.1, I would like to whether we should modify this processing file somehow?

**Comment by lsyysl9711** [comment]
Thanks for replying me!

When I check the codes, I find that in 

https://github.com/styanXDU/TITAN-evaluation-master/blob/97f70a686118c4037f64d134a8fc39f1ca2f697a/titan_eval/utils.py#L201 the codes extract a json file called data.json. But to my best knowledge, in "data/titan-preprocessed/" there is no such file called data.json. 

I suppose that the data.json should be the same as the file "data/MULTIWOZ2 2/data.json", but in this json file we do not have the slots "turns" or "utterances"(https://github.com/styanXDU/TITAN-evaluation-master/blob/97f70a686118c4037f64d134a8fc39f1ca2f697a/titan_eval/utils.py#L206). So I would like to know if this file is missing or we should generate this file by some other scripts?

By the way, I still do not find value_set.json file in "data/MULTIWOZ2 2/". I think this file is necessary in pre-processing stage.

One suggestion is that since there is no preprocessing file in this directory, I think we should move the preprocessing file from https://github.com/styanXDU/TITAN into the current repo.

**Comment by styanXDU** [comment]
We will check the files and write back to you.

2023-09-18 11:36:13"Suyu Liu" ***@***.***>写道：

Thanks for replying me!

When I check the codes, I find that in

https://github.com/styanXDU/TITAN-evaluation-master/blob/97f70a686118c4037f64d134a8fc39f1ca2f697a/titan_eval/utils.py#L201 the codes extract a json file called data.json. But to my best knowledge, in "data/titan-preprocessed/" there is no such file called data.json.

I suppose that the data.json should be the same as the file "data/MULTIWOZ2 2/data.json", but in this json file we do not have the slots "turns" or "utterances"(https://github.com/styanXDU/TITAN-evaluation-master/blob/97f70a686118c4037f64d134a8fc39f1ca2f697a/titan_eval/utils.py#L206). So I would like to know if this file is missing or we should generate this file by some other scripts?

By the way, I still do not find value_set.json file in "data/MULTIWOZ2 2/". I think this file is necessary in pre-processing stage.

One suggestion is that since there is no preprocessing file in this directory, I think we should move the preprocessing file from https://github.com/styanXDU/TITAN into the current repo.

**Comment by lsyysl9711** [comment]
I tried to borrow the preprocessing codes from another repo but it failed in several cases:


1. Missing value_set.json file.

2. Missing mapping.pair file.

3. ![d81db28987a14a810155a9929b68874](https://github.com/styanXDU/TITAN-evaluation-master/assets/71112568/ddbe0dbe-01c4-47bd-ba8f-4884a916ba2a)

    In your proposed dataset, we only use five domains and there is no annotation for the remained two domains, while on the other hand the value_set.json in another repo contains these two missing domains. So there exist mismatches among the annotation file and value_set.json. One solution is to filter out the non-selected domains by keywords, but I want to confirm whether there exists a valid value_set.json file for TITAN instead of borrowing from another repo.

Thanks!

**Comment by lsyysl9711** [comment]
Any updation?😉
